version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: vaccination-portal-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: vaccination-portal-server
    depends_on:
      - postgres
    environment:
      - PORT=5000
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=vaccination_portal
      - JWT_SECRET=vaccination_portal_secret_key
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vaccination-portal-client
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data: